### PR TITLE
Using Git's submodules instead of a Bash script for deps.

### PR DESCRIPTION
**Pull request by kapstok**
### Advantages of using submodules
* Submodules are supported by Linux, Windows and OS X, instead of bash script that can only be executed on Linux distros.
* Compatibility: Submodules keep track of a certain commit instead of a branch. This way a new commit can't break this repository due to massive changes.
* Submodules can be downloaded recursively. If someone uses this repository as a submodule in his or her repo, all of the submodules in both repositories can be downloaded with only one command/flag.

### Disadvantages of using submodules
* Maintainability: To get the newest updates from submodules, you need to pull new commits and push to this repository.

### CODE REVIEW

**Comment by azadkuh** [comment]
thanx for this PR.
i used to manage the 3rdparty repos by sub(sob)-modules and i'm fairly aware of it's pros/cons.
to be honest it never wins my heart and i prefer bash/python scripts to manage my repos by far.

i'm wondering if it's better to include both submodules and the bash-script to satisfy every one!

**Comment by kapstok** [comment]
Thanks for the response. I'll keep my fork online. People will have the choice between submodules and bash scripts :)

Or do you imply that I should include both the ```.gitsubmodules``` and the ```update-dependencies.sh``` file to the PR, so there is just one repo to make everyone happy?

**Comment by kapstok** [comment]
Thanks for the response :)
I could add the ```update-depencies.sh``` file to the PR if you'd like to. It sounds good to me, giving people the choice how they want to obtain the 3rdparty repos.

**Comment by azadkuh** [comment]
dear @kapstok 
yes, exactly. thank you so much.

**Comment by kapstok** [comment]
You're welcome @azadkuh :)
I commited the changes.

**Pull request merged**
